Fix
Fix

diff --git a/Mint/KDE_PLASMA/sources/functions/functions b/Mint/KDE_PLASMA/sources/functions/functions
--- a/Mint/KDE_PLASMA/sources/functions/functions
+++ b/Mint/KDE_PLASMA/sources/functions/functions
@@ -1,31 +1,97 @@
 #! /bin/bash
 
+function check_uninstalled {
+  local package
+  list=""
+  while read -r package; do
+    [ -z "${package}" ] && continue
+
+        STR="${package}"
+        SUB='*'
+
+        case $STR in
+
+          *"$SUB"*)
+            list="${list} ${STR}"
+            ;;
+        esac
+
+    if dpkg -s "${package}" >/dev/null 2>&1; then
+       #show_listitem "Purging ${package}."
+       #sudo apt purge --autoremove "${package}"n
+      list="${list} ${package}"
+    fi
+  done < "${1}"
+  c="sudo nala remove --purge "${list}" -y"
+  eval $c
+  sudo nala autoremove -y
+  sudo nala install -f
+  sudo nala clean
+  sudo apt-get autoclean
+  clear
+}
+
+function check_installed {
+  echo "check_installed"
+  sleep 5
+  local package
+  list=""
+
+  while read -r package; do
+    [ -z "${package}" ] && continue
+
+        STR="${package}"
+        SUB='*'
+
+        case $STR in
+
+          *"$SUB"*)
+            list="${list} ${STR}"
+            ;;
+        esac
+
+    # Check if package is installed already before installing.
+    if dpkg -s "${package}" >/dev/null 2>&1; then
+
+    else
+       #First check if the package exists in the repos.
+      if ! (apt-cache showsrc "${package}" 2>&1 | grep -q "W: "); then
+        #show_listitem "Installing ${package}."
+        #sudo apt-get -y install "${package}"
+        list="${list} ${package}"
+      fi
+    fi
+  done < "${1}"
+  c="sudo nala install "${list}" -y"
+  echo $c
+  sleep 5
+  #eval $c
+}
+
 function uninstall_xfce {
-clear
-echo "UNINSTALL XFCE"
-check_uninstalled "${xfce}"
+ check_uninstalled "${xfce}"
 
+ clear
+ echo "UNINSTALL XFCE: Fix missing"
+ sudo apt-get update --fix-missing
+ sudo apt-get install -f
 
-# echo "UNINSTALL XFCE: Fix missing"
-# sudo apt-get update --fix-missing
-# sudo apt-get install -f
-#
-#
-# echo "UNINSTALL XFCE: Remove folders"
-# sudo rm /usr/share/xfce4/ -rf
-# sudo rm /usr/share/thunar/ -rf
-# sudo rm /usr/share/themes/Mint* -rf
-# sudo rm /usr/share/themes/mint* -rf
-# sudo rm /usr/share/Thunar -rf
-#
-#
-# echo "UNINSTALL XFCE: Update & clean"
-# sudo nala update; sudo nala upgrade -y; sudo nala install -f; sudo dpkg --configure -a; sudo nala autoremove; sudo apt --fix-broken install
-# sudo nala remove initramfs-tools -y
-# sudo nala clean -y
-# sudo nala install initramfs-tools -y
-# sudo apt-get update --fix-missing
-# sudo nala install -f
+ clear
+ echo "UNINSTALL XFCE: Remove folders"
+ sudo rm /usr/share/xfce4/ -rf
+ sudo rm /usr/share/thunar/ -rf
+ sudo rm /usr/share/themes/Mint* -rf
+ sudo rm /usr/share/themes/mint* -rf
+ sudo rm /usr/share/Thunar -rf
+
+ clear
+ echo "UNINSTALL XFCE: Update & clean"
+ sudo nala update; sudo nala upgrade -y; sudo nala install -f; sudo dpkg --configure -a; sudo nala autoremove; sudo apt --fix-broken install
+ sudo nala remove initramfs-tools -y
+ sudo nala clean
+ sudo nala install initramfs-tools -y
+ sudo apt-get update --fix-missing
+ sudo nala install -f
 }
 
 function add_repos(){
@@ -123,27 +189,26 @@ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flat
 
 function install_kde()
 {
-clear
-echo "KDE PLASMA"
-check_installed "${kde_plasma}"
-sudo systemctl set-default graphical.target
-sudo systemctl enable sddm
-lookandfeeltool -a org.kde.breezedark.desktop
-sudo lookandfeeltool -a org.kde.breezedark.desktop
-sudo nala install plasma-discover-backend-flatpak -y
+ echo "KDE PLASMA 2"
+ check_installed "${kde_plasma}"
+ #sudo systemctl set-default graphical.target
+ #sudo systemctl enable sddm
+ #lookandfeeltool -a org.kde.breezedark.desktop
+ #sudo lookandfeeltool -a org.kde.breezedark.desktop
+ #sudo nala install plasma-discover-backend-flatpak -y
 
-#CLEAN PLASMA
-clear
-echo "KDE PLASMA: Remove apps and bloatware"
-check_uninstalled "${kde_bloatware}"
-sudo apt-get update --fix-missing
-sudo apt-get install -f
+ ##CLEAN PLASMA
+ #clear
+ #echo "KDE PLASMA: Remove apps and bloatware"
+ #check_uninstalled "${kde_bloatware}"
+ #sudo apt-get update --fix-missing
+ #sudo apt-get install -f
 
 
-#KDE'S apps
-clear
-echo "KDE PLASMA: KDE'S apps"
-check_installed "${kde_plasma_apps}"
+ ##KDE'S apps
+ #clear
+ #echo "KDE PLASMA: KDE'S apps"
+ #check_installed "${kde_plasma_apps}"
 }
 
 
