Fix
Fix

diff --git a/Mint/KDE_PLASMA/sources/functions/functions b/Mint/KDE_PLASMA/sources/functions/functions
--- a/Mint/KDE_PLASMA/sources/functions/functions
+++ b/Mint/KDE_PLASMA/sources/functions/functions
@@ -1,4 +1,6 @@
 #! /bin/bash
+
+#####################AUX FUNCTIONS ########################
 function check_installed {
   local package
   while read -r package; do
@@ -36,6 +38,222 @@ function check_uninstalled {
   sudo apt-get clean
   sudo apt-get autoclea
 }
+
+##################### AUX FUNCTIONS ########################
+
+function uninstall_xfce {
+clear
+echo "UNINSTALL XFCE"
+check_uninstalled "${xfce}"
+
+clear
+echo "UNINSTALL XFCE: Fix missing"
+sudo apt-get -f install
+sudo apt-get clean
+sudo apt-get autoclean
+sudo apt-get update --fix-missing
+sudo apt-get install -f
+
+clear
+echo "UNINSTALL XFCE: Remove folders"
+sudo rm /usr/share/xfce4/ -rf
+sudo rm /usr/share/thunar/ -rf
+sudo rm /usr/share/themes/Mint* -rf
+sudo rm /usr/share/themes/mint* -rf
+sudo rm /usr/share/Thunar -rf
+
+clear
+echo "UNINSTALL XFCE: Update & clean"
+sudo apt update; sudo apt upgrade -y; sudo apt install -f; sudo dpkg --configure -a; sudo apt-get autoremove; sudo apt --fix-broken install; sudo update-apt-xapian-index
+sudo apt remove initramfs-tools -y
+sudo apt clean
+sudo apt install initramfs-tools -y
+sudo apt-get update --fix-missing
+sudo apt-get install -f
+
+}
+
+function add_repos(){
+sudo add-apt-repository multiverse -y
+
+##### KERNEL INSTALLER ####
+sudo add-apt-repository ppa:cappelikan/ppa -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/mainline.gpg
+sudo ln -s /etc/apt/mainline.gpg /etc/apt/trusted.gpg.d/mainline.gpg
+
+##### NVIDIA ####
+sudo add-apt-repository ppa:graphics-drivers/ppa -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/nvidia.gpg
+sudo ln -s /etc/apt/nvidia.gpg /etc/apt/trusted.gpg.d/nvidia.gpg
+
+##### GRUB CUSTOMIZER ####
+sudo add-apt-repository ppa:danielrichter2007/grub-customizer -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/grub-customizer.gpg
+sudo ln -s /etc/apt/grub-customizer.gpg /etc/apt/trusted.gpg.d/grub-customizer.gpg
+
+##### APP IMAGE LAUNCHER ####
+sudo add-apt-repository ppa:appimagelauncher-team/stable -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/appimagelauncher.gpg
+sudo ln -s /etc/apt/appimagelauncher.gpg /etc/apt/trusted.gpg.d/appimagelauncher.gpg
+
+##### KUBUNTU BACKPORTS ####
+sudo add-apt-repository ppa:kubuntu-ppa/backports -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/kubuntu_backports.gpg
+sudo ln -s /etc/apt/kubuntu_backports.gpg /etc/apt/trusted.gpg.d/kubuntu_backports.gpg
+
+##### KUBUNTU BACKPORTS EXTRAS ####
+sudo add-apt-repository ppa:kubuntu-ppa/backports-extra -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/kubuntu_backports_extra.gpg
+sudo ln -s /etc/apt/kubuntu_backports_extra.gpg /etc/apt/trusted.gpg.d/kubuntu_backports_extra.gpg
+
+##### UBUNTU STUDIO BACKPORTS ####
+sudo add-apt-repository ppa:ubuntustudio-ppa/backports -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/ubuntustudio.gpg
+sudo ln -s /etc/apt/ubuntustudio.gpg /etc/apt/trusted.gpg.d/ubuntustudio.gpg
+
+##### PIPEWIRE ####
+sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/pipewire.gpg
+sudo ln -s /etc/apt/pipewire.gpg /etc/apt/trusted.gpg.d/pipewire.gpg
+
+##### WIREPLUMBER ####
+sudo add-apt-repository ppa:pipewire-debian/wireplumber-upstream -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/wireplumber.gpg
+sudo ln -s /etc/apt/wireplumber.gpg /etc/apt/trusted.gpg.d/wireplumber.gpg
+
+###### QBITTORRENT ####
+sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable -y
+##Fix deprecated Key MINT issue
+sudo mv /etc/apt/trusted.gpg /etc/apt/qbittorrent.gpg
+sudo ln -s /etc/apt/qbittorrent.gpg /etc/apt/trusted.gpg.d/qbittorrent.gpg
+
+###### BRAVE BROWSER ####
+sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
+echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
+
+###### ONLY OFFICE ####
+mkdir -p ~/.gnupg
+chmod 700 ~/.gnupg
+gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
+chmod 644 /tmp/onlyoffice.gpg
+sudo chown root:root /tmp/onlyoffice.gpg
+sudo mv /tmp/onlyoffice.gpg /etc/apt/trusted.gpg.d/
+echo 'deb https://download.onlyoffice.com/repo/debian squeeze main' | sudo tee -a /etc/apt/sources.list.d/onlyoffice.list
+
+###### BALENA ETCHER ####
+curl -1sLf \
+   'https://dl.cloudsmith.io/public/balena/etcher/setup.deb.sh' \
+   | sudo -E bash
+
+
+   ##### CLEAN ANH GET MISSINGS KEYS ####
+sudo apt update 2>&1 1>/dev/null | sed -ne 's/.NO_PUBKEY //p' | while read key; do if ! [[ ${keys[]} =~ "$key" ]]; then sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+=("$key"); fi; done
+sudo apt update -y
+clear
+
+##### FLATPACKS ####
+sudo apt install flatpak -y
+flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+
+
+}
+
+function install_kde()
+{
+clear
+echo "KDE PLASMA"
+check_installed "${kde_plasma}"
+sudo systemctl set-default graphical.target
+sudo systemctl enable sddm
+lookandfeeltool -a org.kde.breezedark.desktop
+sudo lookandfeeltool -a org.kde.breezedark.desktop
+sudo apt install plasma-discover-backend-flatpak -y
+
+#CLEAN PLASMA
+clear
+echo "KDE PLASMA: Remove apps and bloatware"
+check_uninstalled "${kde_bloatware}"
+
+sudo apt -y autoremove
+sudo apt-get -f install
+sudo apt-get clean
+sudo apt-get autoclean
+
+
+#KDE'S apps
+clear
+echo "KDE PLASMA: KDE'S apps"
+check_installed "${kde_plasma_apps}"
+}
+
+function install_core_apps()
+{
+clear
+echo "CORE APPS"
+
+#Development tools and libraries
+check_installed "${tools}"
+
+curl https://sh.rustup.rs -sSf | sh
+source ~/.profile
+source ~/.cargo/env
+
+#Codecs and Drivers
+check_installed "${codecs}"
+
+#Utilities
+check_installed "${utilities}"
+
+cargo install --git https://github.com/Peltoche/lsd.git --branch master
+#falta el alias de batch"
+
+sudo npm install -g hblock
+hblock
+
+
+#PIPEWIRE & WIREPLUMBER
+sudo apt install -y libfdk-aac2 libldacbt-{abr,enc}2 libopenaptx0
+sudo apt install -y gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,bin,locales,tests}}
+sudo apt install -y pipewire-doc
+sudo apt-get install -y wireplumber{,-doc} gir1.2-wp-0.4 libwireplumber-0.4-{0,dev}
+systemctl --user --now disable pulseaudio.{socket,service}
+systemctl --user mask pulseaudio
+systemctl --user --now enable pipewire{,-pulse}.{socket,service}
+systemctl --user --now enable wireplumber.service
+
+#NERD FONTS
+mkdir /tmp/nerd_fonts/
+wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip -P /tmp/nerd_fonts/
+wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Ubuntu.zip -P /tmp/nerd_fonts/
+wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Mononoki.zip -P /tmp/nerd_fonts/
+
+sudo unzip /tmp/nerd_fonts/JetBrainsMono.zip -d /tmp/nerd_fonts/JetBrainsMono
+sudo unzip /tmp/nerd_fonts/Ubuntu.zip -d /tmp/nerd_fonts/Ubuntu/
+sudo unzip /tmp/nerd_fonts/Mononoki.zip -d /tmp/nerd_fonts/Mononoki/
+
+sudo mkdir /usr/share/fonts/nerd_fonts/
+sudo mv /tmp/nerd_fonts/JetBrainsMono/*.ttf /usr/share/fonts/nerd_fonts/
+sudo mv /tmp/nerd_fonts/Ubuntu/*.ttf /usr/share/fonts/nerd_fonts/
+sudo mv /tmp/nerd_fonts/Mononoki/*.ttf /usr/share/fonts/nerd_fonts/
+sudo mv /tmp/nerd_fonts/JetBrainsMono/*.otf /usr/share/fonts/nerd_fonts/
+sudo mv /tmp/nerd_fonts/Ubuntu/*.otf /usr/share/fonts/nerd_fonts/
+sudo mv /tmp/nerd_fonts/Mononoki/*.otf /usr/share/fonts/nerd_fonts/
+sudo rm /tmp/nerd_fonts/ -rf
+sudo apt install -y fonts-noto-color-emoji
+sudo cp Files/fonts.conf /etc/fonts/fonts.conf -rf
+fc-cache -f -v
+}
+
+
 
 function install_ZSH()
 {
@@ -127,91 +345,5 @@ else
     echo -e "Something is wrong"
 fi
 exit
-
-}
-
-
-
-function add_repos(){
-sudo add-apt-repository multiverse -y
-
-##### KERNEL INSTALLER ####
-sudo add-apt-repository ppa:cappelikan/ppa -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/mainline.gpg
-sudo ln -s /etc/apt/mainline.gpg /etc/apt/trusted.gpg.d/mainline.gpg
-
-##### NVIDIA ####
-sudo add-apt-repository ppa:graphics-drivers/ppa -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/nvidia.gpg
-sudo ln -s /etc/apt/nvidia.gpg /etc/apt/trusted.gpg.d/nvidia.gpg
-
-##### GRUB CUSTOMIZER ####
-sudo add-apt-repository ppa:danielrichter2007/grub-customizer -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/grub-customizer.gpg
-sudo ln -s /etc/apt/grub-customizer.gpg /etc/apt/trusted.gpg.d/grub-customizer.gpg
-
-##### APP IMAGE LAUNCHER ####
-sudo add-apt-repository ppa:appimagelauncher-team/stable -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/appimagelauncher.gpg
-sudo ln -s /etc/apt/appimagelauncher.gpg /etc/apt/trusted.gpg.d/appimagelauncher.gpg
-
-##### KUBUNTU BACKPORTS ####
-sudo add-apt-repository ppa:kubuntu-ppa/backports -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/kubuntu_backports.gpg
-sudo ln -s /etc/apt/kubuntu_backports.gpg /etc/apt/trusted.gpg.d/kubuntu_backports.gpg
-
-##### KUBUNTU BACKPORTS EXTRAS ####
-sudo add-apt-repository ppa:kubuntu-ppa/backports-extra -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/kubuntu_backports_extra.gpg
-sudo ln -s /etc/apt/kubuntu_backports_extra.gpg /etc/apt/trusted.gpg.d/kubuntu_backports_extra.gpg
-
-##### UBUNTU STUDIO BACKPORTS ####
-sudo add-apt-repository ppa:ubuntustudio-ppa/backports -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/ubuntustudio.gpg
-sudo ln -s /etc/apt/ubuntustudio.gpg /etc/apt/trusted.gpg.d/ubuntustudio.gpg
-
-##### PIPEWIRE ####
-sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/pipewire.gpg
-sudo ln -s /etc/apt/pipewire.gpg /etc/apt/trusted.gpg.d/pipewire.gpg
-
-##### WIREPLUMBER ####
-sudo add-apt-repository ppa:pipewire-debian/wireplumber-upstream -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/wireplumber.gpg
-sudo ln -s /etc/apt/wireplumber.gpg /etc/apt/trusted.gpg.d/wireplumber.gpg
-
-###### QBITTORRENT ####
-sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable -y
-##Fix deprecated Key MINT issue
-sudo mv /etc/apt/trusted.gpg /etc/apt/qbittorrent.gpg
-sudo ln -s /etc/apt/qbittorrent.gpg /etc/apt/trusted.gpg.d/qbittorrent.gpg
-
-###### BRAVE BROWSER ####
-sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
-echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
-
-###### ONLY OFFICE ####
-mkdir -p ~/.gnupg
-chmod 700 ~/.gnupg
-gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
-chmod 644 /tmp/onlyoffice.gpg
-sudo chown root:root /tmp/onlyoffice.gpg
-sudo mv /tmp/onlyoffice.gpg /etc/apt/trusted.gpg.d/
-echo 'deb https://download.onlyoffice.com/repo/debian squeeze main' | sudo tee -a /etc/apt/sources.list.d/onlyoffice.list
-
-###### BALENA ETCHER ####
-curl -1sLf \
-   'https://dl.cloudsmith.io/public/balena/etcher/setup.deb.sh' \
-   | sudo -E bash
-
 
 }
